### ISSUE TITLE
Use of 'Not' in Choice state

### ISSUE THREAD

**Issue by pmotyka** [wmfs/statebox#271]
Hi!  I've observed the following behavior when using 'Not' in a Choice state.  The state machine definition passes lint'ing, so I'm assuming it is indeed a valid definition:

```
Statebox is ready
{
  executionName: '1',
  ctx: { data: { foo: 'bar', baz: 'bam' }, visibility: 'Private' },
  currentStateName: 'OperatorChoice',
  currentResource: undefined,
  stateMachineName: 'visibility',
  status: 'FAILED',
  executionOptions: {
    error: {
      error: 'AssertionError',
      cause: 'we need a path',
      stack: 'AssertionError [ERR_ASSERTION]: we need a path\n' +
        '    at JSONPath.query (/private/tmp/statebox-test/node_modules/jsonpath/lib/index.js:92:10)\n' +
        '    at InputValueCache.get (/private/tmp/statebox-test/node_modules/@wmfs/asl-choice-processor/lib/Input-value-cache.js:17:20)\n' +
        '    at Choice.calculateNextState (/private/tmp/statebox-test/node_modules/@wmfs/asl-choice-processor/lib/index.js:12:37)\n' +
        '    at Choice.process (/private/tmp/statebox-test/node_modules/@wmfs/statebox/lib/state-machines/state-types/Choice.js:17:32)\n' +
        '    at Choice.run (/private/tmp/statebox-test/node_modules/@wmfs/statebox/lib/state-machines/state-types/Base-state.js:39:19)\n' +
        '    at StateMachine.runState (/private/tmp/statebox-test/node_modules/@wmfs/statebox/lib/state-machines/State-machine.js:56:30)\n' +
        '    at StateMachine.processState (/private/tmp/statebox-test/node_modules/@wmfs/statebox/lib/state-machines/State-machine.js:88:17)'
    }
  },
  startDate: '2020-07-29T22:08:17.691Z',
  errorCode: 'AssertionError',
  errorMessage: 'we need a path'
}
```

Example via gist - https://gist.github.com/pmotyka/13afcf422e9fa645639ca6728b8f0a8f, thanks!

**Comment by pmotyka** [comment]
Ah, looks like a TODO - https://github.com/wmfs/asl-choice-processor/blob/master/lib/operators/not.js

**Comment by pmotyka** [comment]
Going to close this since it's not defective behavior, thanks!
